### ISSUE TITLE
When I try to start the game it says , "Windows cannot find 'C:\Users\user\Downloads\GameFiles\flashplayer_32_sa.exe'. 

### ISSUE THREAD

**Issue by verycoffee** [DoctorQwack/Obliterate-Everything-3-Unlocked#1]

**Comment by DoctorQwack** [comment]
RunGame.bat and the folder "game files" should be in the same parent folder
 If you move the folder "game files" or the "runGame.bat" file, it will no longer be able to find the necessary files for the game.

Maybe try re-installing the files and let me know if anything changes.

**Comment by verycoffee** [comment]
I installed the files again and the same issue happens. This is what it looks like in winrar without me moving anything.
![image](https://user-images.githubusercontent.com/132142749/235550353-c3d698cd-520d-488e-8b1e-90f76b080627.png)
Then I double click on RunGame.bat and get the same error.
![image](https://user-images.githubusercontent.com/132142749/235550411-a050fd22-daa0-4e1c-b67e-1e6db86e5ac2.png)

**Comment by DoctorQwack** [comment]
Did you extract the files first? The system can't find the files properly
when they are still compressed in the ZIP.

**Comment by verycoffee** [comment]
No I didn't, I'll try that now.

**Comment by verycoffee** [comment]
It works now, thanks.
